### PR TITLE
Provide timing info in socket timeout errors

### PR DESCRIPTION
**Pull request by broofa**
Helps with timeout diagnostics

### CODE REVIEW

**Comment by patrickjuchli** [comment]
How does that help timeout diagnostics?

**Comment by patrickjuchli** [comment]
There are two points I'd like to make here.

Assuming timeout works the way you probably think it's working in in this library: Isn't the time difference you calculate exactly the same duration specified as `timeout`? I still don't see how this provides more insight when looking at how Node.js timeouts work.

More importantly though: This would work for data connections but timeout for control connections work differently. Regardless of what your desired timeout is, it's 0 at first.

https://github.com/patrickjuchli/basic-ftp/blob/1b8ae5a577f6fad996eac4ffb6553593900ddcb8/lib/FtpContext.js#L163

Then, if a task begins, timeout is activated:

https://github.com/patrickjuchli/basic-ftp/blob/1b8ae5a577f6fad996eac4ffb6553593900ddcb8/lib/FtpContext.js#L300

And deactivated when the task finishes:

https://github.com/patrickjuchli/basic-ftp/blob/1b8ae5a577f6fad996eac4ffb6553593900ddcb8/lib/FtpContext.js#L311

Control socket timeout is also deactivated while a transfer is happening. Because during that time, the data connection is used to track timeout.

**Comment by broofa** [comment]
> Isn't the time difference you calculate exactly the same duration specified as timeout?

No, this shows the time between the `connect` and `timeout` events, which is equal to `active_time + timeout`.  The unknown here being `active_time`.   For example, on my client which is periodically timing out I see the following:

```
Timeout after 61.216 seconds (control socket)
Timeout after 155.266 seconds (control socket)
Timeout after 54.642 seconds (control socket)
Timeout after 120.034 seconds (control socket)
Timeout after 1346.029 seconds (control socket)
Timeout after 32.691 seconds (control socket)
Timeout after 15.069 seconds (control socket)
Timeout after 93.401 seconds (control socket)
Timeout after 74.491 seconds (control socket)
...
```
I actually originally thought this was something related to this module but seeing the above helped me realize it's more likely a network issue or something specific to the server. 

> Regardless of what your desired timeout is, it's 0 at first.

This isn't about the desired or configured timeout.  It's about surfacing the amount of time the socket was open for.

**Comment by patrickjuchli** [comment]
I have never seen this kind of information presented to me when there is a timeout. "Timeout after X seconds" definitely misled me – I'm reading this as the timeout-time, not the time "since the socket was opened". I wouldn't know what to do with this information… in this total time there would be everything: Other processes, network latency and speed, etc.

This doesn't provide clarity but raises more questions, I can't merge this.

But I'm interested in learning more about where this all started. You had some timeout issues and didn't know why. What made you distrust the library?

**Comment by broofa** [comment]
Yeah, I agree the message is a little misleading.   And you're right, typically you don't see this information.

> What made you distrust the library?

It's not that I distrust the library, per se, it's that the error handling abstraction got in the way of understanding what was happening.  It told me an error occurred, but not _when_ it occured.

> Maybe it would help to have the README explain how timeouts work in the library?

Nah, that's in the [Node docs](https://nodejs.org/api/net.html#net_socket_settimeout_timeout_callback).  I think the most helpful thing you could put in the README is an example of how to handle errors.  The boilerplate for that seems to be non-trivial.  For example, I've landed on the following pattern:
```
let client;  // "global" client

// ...

function runFtpTask() {
  // Client session setup
  if (!client || client.ftp.socket.destroyed) {
    client = new Ftp.Client();
    await client.access({host: HOST, user: USER});
  }

  try {
    await client.download();
  } catch (err) {
    if (client.ftp.socket.destroyed)  {
      // Client session tear down
    }
    console.warn(`FTP Error: ${err.message}`);
  } finally {
    // Task tear down
  }
}
```

(... and am I doing this right?   E.g. Is `client.ftp.socket.destroyed` the best way to detect if the client has closed?)

**Comment by broofa** [comment]
> Why do you need a global instance of the client?

1. Setting up/tearing down a client on every task is inefficient (Overhead of TCP socket connections + overhead of USER/PASS auth)
2. ... and unintuitive.  FTP is session-based.  You login, you do what you need to do, then you logout.  In my case, I need to download lots of files for an indefinite amount of time.  If that first example is how you expect this library to be used, then you should get rid of the `access()`, `connect()`, and `close()` methods and, instead, just have "setOptions".  Then make each task function responsible for connecting and closing, so users aren't forced to copy paste that code everywhere. 
3. The server we're talking to is unfortunately brittle.  If we stress it too much, it stops working.  I'm trying to limit the amount of network/socket churn we throw at it.
4. There's also the TCP connection being a good proxy for the robot status, although the error handling abstraction kind of kills that perk for us.  I may come back to it at some point, however.

**Pull request closed without merging**
