### PR TITLE
chore: remove trailing whitespace & eslint enhancements

### PR DESCRIPTION
**Pull request by broofa**
Sorry, 'meant this to be a simple commit to remove the trailing whitespace, but ...
* ... saw the `eslintrc` file so added the `no-trailing-whitespace` rule there
* ... and added `eslint` to the `npm test` command to enforce eslint rules (2nd commit)
* ... which caused tests to fail
* ... so ran `eslint --fix .` to fixup the whitespace and indent issues
* ... and cleaned up the remaining issues (3rd commit)

*sigh*... sorry. :-)

### CODE REVIEW

**Comment by patrickjuchli** [comment]
Let’s start with this PR, thanks for the cleanup. I don’t see the rule being added to eslintrc, though. Could you add that? Do we need an exception for comments?

**Comment by patrickjuchli** [comment]
I see, CI is not checking linting right now... I‘m ok with including linting in `npm test` then, but `npm run lint` should target `.` as well.

**Comment by broofa** [comment]
Added no-trailing-spaces rule, ran `eslint --fix .` which apparently caught some trailing whitespace I didn't find in the first commit.  `lint` now targets `.` dir.

I agree `lint` and `test` are two different operations, but if `lint` isn't part of the core workflow it tends to get ignored.  Ideally it's run as a `pre-commit` hook I'm not sure there's a good way to enforce that on public github projects (`[husky](https://github.com/typicode/husky)` maybe?)  (Running `lint` in CI I find more frustrating than helpful.  "Seriously?  CI is breaking because I have trailing whitespace???")

> Do we need an exception for comments?

Nah.  I've had my IDE set this way for *years*.  It's never been an issue.

**Comment by patrickjuchli** [comment]
Thank you!

I can have a look at the UTF-8 bug maybe Thursday or Friday. After that I‘ll have a look at the other issues/pull requests.

**Pull request merged**
